apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-kub
  namespace: hello-kub
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-kub
    spec:
      containers:
      - image: ohad24/hello_kub_img:latest
        name: hello-kub
