apiVersion: v1
kind: Service
metadata:
  name: hello-kub
  namespace: hello-kub
spec:
  type: NodePort
  ports:
  - name: "hello-kub-service"
    port: 5000
    targetPort: 5000
    nodePort: 32000
  selector:
    app: hello-kub

