apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kub
  namespace: hello-kub
  labels:
    app: hello-kub
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-kub
  template:
    metadata:
      labels:
        app: hello-kub
    spec:
      containers:
      - image: ohad24/hello_kub_img:latest
        name: hello-kub
